# Generated by Django 3.0.2 on 2020-01-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wav2midi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
    ]
